//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dayfour
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_
    {
        public int IDOperation { get; set; }
        public Nullable<int> TypeOperation { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> NumberAccount { get; set; }
    
        public virtual BankAccount_ BankAccount_ { get; set; }
        public virtual TypeOperation_ TypeOperation_ { get; set; }
    }
}
